### PR TITLE
Support iOS 12.2 (Fix #138)

### LINKED ISSUE #138: Stopped Working after iOS v 12.2 upgrade
The tool stopped working after the most recent iOS v12.2 release.
It was working for me on Window 7 Chrome + iPhone 7Plus until my phone just updated to iOS v12.2 (16E227).
The chrome://inspect/#devices only shows a service worker to inspect. It does not discover or allow me to inspect the url I have loaded in my phones Safari Browser.
I updated my iTunes and the ios_webkit_debug_proxy + remotedebug_ios_webkit_adapter to the most current version but it is still notr working.

The logging within the powershell remotedebug_ios_webkit_adapter --port=9222 window behaves the same as it did when it was working prior to the iOS update.
Does anyone have it working on a Windows PC with an iOS v12.2 device attached?

### PR DESCRIPTION
**Pull request by fishbone1**
See https://github.com/RemoteDebug/remotedebug-ios-webkit-adapter/issues/138

### CODE REVIEW

**Comment by Sardtok** [comment]
I tried applying this patch, but got errors on accessing fields of a message in the screencast protocol. I think it has something to do with the unwrapping added to the handler for messages from target. It's easy enough to fix by short-circuiting, but the connection gets closed right after.

**Comment by auchenberg** [comment]
Looks like quite some changes in the protocol handling. Has this been tested with iOS 11 to ensure backwards compatibility isn’t broken?

**Comment by KaelWD** [comment]
- Console is still broken too, only the first `console.log` argument is shown and I can't run any commands myself. 
 - Breakpoints work and the debugger shows scopes but they're all empty, can't inspect variables

**Comment by bilalhusain** [comment]
It appears that the wrapping and unwrapping changes can be done in `src/protocols/target.ts` alone. I could get the console and screencast working. The approach is mostly what the pull request suggests:

1. Add a new field to keep track of "targetId"

```
    private _targetId: string;
```

2. Unwrap message when received by websocket

```
    this._wsTarget.on('message', (message) => {
        const msg = JSON.parse(message);
        switch (msg.method) {
            case 'Target.targetCreated':
                this._targetId = msg.params.targetInfo.targetId;
                break;
            case 'Target.dispatchMessageFromTarget':
                if (msg.params && msg.params.message) {
                    message = msg.params.message;
                }
                this.onMessageFromTarget(message);
                break;
            default:
                // ignore
        }
    });
```

3. Wrap message before sending to websocket (`sendToTarget`)

```
    const msg = JSON.parse(rawMessage);
    rawMessage = JSON.stringify({
        id: msg.id,
        method: 'Target.sendMessageToTarget',
        params: {
            message: rawMessage,
            targetId: this._targetId
        }
    });
```

To handle backwards compatibility, the wrapping and unwrapping can be done conditionally. However, the biggest change seems to be waiting for the first message (message with method `Target.targetCreated`) which contains the "targetId" and then only emptying the `_messageBuffer` (this is currently being done as soon as we get websocket "open"). This "waiting" has no affect on older versions and we will get stuck "waiting", so, there needs to be some workaround, e.g., pushing an empty message to trigger the first (error) message or timing out the "waiting". Alternatively, the version can be configuration driven.

**Comment by ewanharris** [comment]
I can confirm that this does break usage on iOS 11. We'll probably need to update it to only run these on iOS 12.2 an above.

@bilalhusain thanks for your comment! It'll totally be helpful in tackling this.

**Comment by Fr33maan** [comment]
@ewanharris according to some stats, iOS 11.x is only 1.5% market shares while iOS 12.x is 50%.
Supporting iOS 12 seems more important than 11.x.
This PR was a must for me to still be able to debug after upgrading to iOS12.
Maybe creating a new branch ? But I strongly suggest to merge this PR by a way or another as it seems to be a big headache for many people. (50 comments on the issue thread -> https://github.com/RemoteDebug/remotedebug-ios-webkit-adapter/issues/138)

You can also see how much its needed by the amount of forks just in order to support iOS 12

You do great job guys, this library is awesome

cheers <3

**Comment by ewanharris** [comment]
@Fr33maan I believe for a package like this it's important to try and maintain backwards compatibly (especially when it's down to switching based on the OS version rather than a significant technical hurdle).

I haven't had the time I wanted to dedicate to this package, but fortunately awesome folks like @fishbone1 and @petewalker have stepped up and fixed this.

I've merged #177 and published a prerelease so I'm going to close this PR.

**Pull request closed without merging**
